# Generated by Django 3.2.4 on 2021-06-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_id', models.TextField()),
                ('user_name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
