# Generated by Django 3.2.4 on 2021-06-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210609_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_liked',
            new_name='Suggestion',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='user_name',
            new_name='sugs',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='y_id',
            new_name='words',
        ),
    ]
