# Generated by Django 3.2.5 on 2021-07-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210627_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
