# Generated by Django 3.2.5 on 2021-07-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0004_delete_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked_Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('liked_songs_json', models.TextField()),
            ],
        ),
    ]
