# Generated by Django 3.2.5 on 2021-09-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_liked_songs_json_liked_songs_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.TextField()),
                ('n', models.TextField()),
                ('title', models.TextField()),
                ('thumb', models.TextField()),
                ('dur', models.TextField()),
            ],
        ),
    ]
