# Generated by Django 3.2.5 on 2021-09-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_song_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='n',
            field=models.IntegerField(),
        ),
    ]
